spring:  
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/db_fornecedor?serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  server:
    error:
      include-message: always
